config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do 
    resources :comments
  end

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :comment , presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  after_action :authenticate_user!
  
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:comment))
    @comment.user_id = current_user.id if current_user
    #@comment.save

    if @comment.valid?
      if @comment.save
        redirect_to post_path(@post)
    #else
    #  render 'posts/show'
      end
    end
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  def edit 
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def update 
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    if @comment.update(params[:comment].permit(:comment))
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show,:edit,:update,:destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    #@post = Post.new
    @post = current_user.posts.build
  end

  def show
    
  end
  def create
    #@post = Post.new(post_params)
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
.comment.clearfix
  .content
    %p.comment_content= comment.comment
    %p.comment_author= comment.user.email
  .buttons
    = link_to "Delete Reply", [comment.post, comment], method: :delete, data: { confirm: "Are you sure?"}
    = link_to "Edit", edit_post_comment_path(comment.post, comment)

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
  = f.input :comment, :required => true
  = f.submit

app/views/comments/edit.html.haml
%h1 Edit Reply

= simple_form_for([@post, @comment]) do |f|
  = f.input :comment
  = f.submit 

app/views/layouts/application.html.haml
!!! 
%html
%head
  %title FORUM  
  = csrf_meta_tags 
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  %link{ rel: "stylesheet",  href: "https://fonts.googleapis.com/css?family=Pacifico" , type: "text/css" }
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
  %header.main_header.clearfix
    .wrapper 
      #logo 
        %p= link_to "FORUM", root_path 
      #buttons
        - if user_signed_in?
          = link_to "New Post", new_post_path
          = link_to "Sign out", destroy_user_session_path, method: :delete
        - else 
          = link_to "Sign Up", new_user_registration_path
          = link_to "Sign In", new_user_session_path
  .wrapper
    %p.notice= notice 
    %p.alert= alert 
  .wrapper
    = yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  = f.input :title 
  = f.input :content , :required => true
  = f.submit 

app/views/posts/edit.html.haml
%h1 Edit Post

= render 'form'

= link_to "Cancel", post_path

app/views/posts/index.html.haml
#posts
  - @posts.each do |post|
    .post
      %h2.title= link_to post.title, post 
      %p.date
        Published at
        = time_ago_in_words(post.created_at)
        by 
        = post.user.email


  

app/views/posts/new.html.haml
%h1 New Post

= render 'form'

app/views/posts/show.html.haml
#post_content
  %h1= @post.title
  %p= @post.content

  #comments
    %h2
      = @post.comments.count 
      Comments
    = render @post.comments 
    
    - if user_signed_in?
      %h3 Reply to thread 
      = render "comments/form"
  
  %hr/
  %br/

  = link_to "Edit", edit_post_path(@post), class: "button"
  = link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you wanna do this?"}, class: "button"
  = link_to "Home", root_path, class: "button"